# Generated by Django 5.2 on 2025-04-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
